-- Fix embedding dimension from 768 to 384 for local model
-- Model: paraphrase-multilingual-MiniLM-L12-v2

-- Drop existing indexes
DROP INDEX IF EXISTS idx_products_embedding;
DROP INDEX IF EXISTS idx_taxonomy_nodes_embedding;
DROP INDEX IF EXISTS products_embedding_idx;
DROP INDEX IF EXISTS taxonomy_nodes_embedding_idx;

-- Change column types to 384 dimensions
ALTER TABLE products ALTER COLUMN embedding TYPE vector(384);
ALTER TABLE taxonomy_nodes ALTER COLUMN embedding TYPE vector(384);

-- Update comments
COMMENT ON COLUMN products.embedding IS 
'Product embedding vector (384 dimensions).
Generated by: paraphrase-multilingual-MiniLM-L12-v2 (local model via FastAPI)
Same model as FastAPI backend for consistency.';

COMMENT ON COLUMN taxonomy_nodes.embedding IS 
'Vector embedding for category name (384-dim for local model paraphrase-multilingual-MiniLM-L12-v2)';

-- Recreate indexes for 384-dim vectors
CREATE INDEX products_embedding_idx 
ON products USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

CREATE INDEX taxonomy_nodes_embedding_idx 
ON taxonomy_nodes USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 20);

-- Clear existing embeddings (they were 768-dim)
UPDATE products SET embedding = NULL WHERE embedding IS NOT NULL;
UPDATE taxonomy_nodes SET embedding = NULL WHERE embedding IS NOT NULL;
