name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest pytest-cov black isort; fi

      - name: Lint (black & isort)
        run: |
          black --check .
          isort --check-only .

      - name: Run tests (pytest + coverage)
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=. --cov-report=xml

      - name: Upload coverage.xml
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: warn

      # อัปโหลดผลลัพธ์งานของคุณ (เช่น CSV/XLSX ในโฟลเดอร์ outputs/)
      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: job-outputs
          path: |
            outputs/**
          if-no-files-found: ignore
